default: &default
  adapter: mysql2
  database: dataxevent_db
  pool: 5
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: dataxevent_db
  
test:
  <<: *default
  database: dataxevent_db

production:
  <<: *default
  database: 
  username: activestorage_tuto
  password: <%= ENV["ACTIVESTORAGE_TUTO_DATABASE_PASSWORD"] %>
